### PR TITLE
Fixed class_inheritable_accessor deprecation.

### PR DESCRIPTION
**Pull request by dcalhoun**
Replaced class_inheritable_accessor with class_attribute.

### CODE REVIEW

**Comment by safarista** [comment]
It doesnt look like @jongilbraith is maintaining this repo anymore. Could someone else maybe take it over? 

I would be happy to do that.

**Comment by safarista** [comment]
@dcalhoun is your request incorporating the other earlier pull requests or its based on the original branch?

**Comment by dcalhoun** [comment]
@safarista It is purely a fix for the deprecated method.

**Comment by safarista** [comment]
I see. am working through the other "Many changes" request https://github.com/jongilbraith/simple-private-messages/pull/9/files I'll get to this once am done with that.

 Any comments on the url above would be very helpful.

**Comment by safarista** [comment]
I have included the changes in the other one that am working on and its done. Thanks for the input.

**Pull request closed without merging**
